### PR TITLE
initial support for common library

### PR DESCRIPTION
**Pull request by MichaelBrim**
### Description
Started identifying common code between server and client and moving
it to new `common/src` directory, which is compiled to form a new
libunifycr_common library that both the client library and server
will link against.

Major changes include the use of enumerator and configurator from
my MichaelBrim/tedium GitHub repo, which ease management of
enumerated types and configuration settings, respectively.

Error types, consistency types, and resource manager types have been
converted to use enumerator. See `common/src/xxx_enumerator.h` files
for new types and accessor functions.

The server has been updated to use configurator rather than `getenv()`
to determine configuration settings. See `UNIFYCR_CONFIGS` definition
in `common/src/unifycr_configurator.h` for the list of settings.

Note that a few environment variable names have changed. The most
notable is `UNIFYCR_MOUNT_POINT` is now `UNIFYCR_MOUNTPOINT`. The
unit tests have been updated as necessary to accommodate the name changes.

### Motivation and Context

See Issue #117 

### How Has This Been Tested?
Unit tests were updated and run - all passed.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyCR code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by MichaelBrim** [comment]
I don't see any failures in the Travis log - not sure why it "failed". Can someone else check and see if they see something I missed?

**Comment by dsikich** [comment]
@MichaelBrim Looks like style script errors in the second commit. Also, even if you fix those the build will still fail since the first commit failed, even if you fixed the error in the second commit. The way around this is two squash them into one commit, fix the errors, then Travis CI should pass once you fix the style script errors. Are you able to see the build log from Travis when you click on the red X?

**Comment by dsikich** [comment]
Hmm.. I'm not as familiar with the best way to skip checks (haven't done that yet). I think @sandrain has done this, and @nedbass might know better the best way to do that.

**Comment by nedbass** [comment]
@MichaelBrim if the new code is going to be maintained as part of unifycr, it should conform to the project style guidelines and be licensed under the same license.

**Comment by nedbass** [comment]
@MichaelBrim sorry I didn't read your comment carefully. If there are a few remaining style issues that can't or shouldn't be fixed, you can exempt the file by adding a lines like this to your commit message.

```
TEST_CHECKPATCH_SKIP_FILES=common/src/unifycr_configurator.h
TEST_CHECKPATCH_SKIP_FILES+=common/src/ini.h
```

etc.

**Comment by MichaelBrim** [comment]
@nedbass Based on checkpatch.sh, it seems the SKIP_FILES should be comma-separated, but you didn't append commas in the commit message example. I'm assuming I need the comma, correct?

**Comment by MichaelBrim** [comment]
@dsikich I used the existing tests (minor changes to environment variables) to verify functionality.

libunifycr_common is linked into the client library and the unifycrd. You should be able to see that with ldd.

**Comment by dsikich** [comment]
@MichaelBrim hmm... I wonder if I am doing something wrong. I see libunifycr_common in install/lib:

```bash
catalyst160{sikich1}107: ls install/lib
libtap.a   libtap.so.0      libtestutil.la    libtestutil.so.0.0.0  libunifycr.so        libunifycr_common.a   libunifycr_common.so.1      libunifycr_gotcha.la    libunifycr_gotcha.so.1.0.0
libtap.la  libtap.so.0.0.0  libtestutil.so    libunifycr.a          libunifycr.so.1      libunifycr_common.la  libunifycr_common.so.1.0.0  libunifycr_gotcha.so    pkgconfig
libtap.so  libtestutil.a    libtestutil.so.0  libunifycr.la         libunifycr.so.1.0.0  libunifycr_common.so  libunifycr_gotcha.a         libunifycr_gotcha.so.1
```

But I do not see it linked with unify crd:

```bash
catalyst160{sikich1}110: ldd unifycrd
	linux-vdso.so.1 =>  (0x00002aaaaaaab000)
	libleveldb.so.1 => /g/g0/sikich1/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/leveldb-1.20-bxwxfvdm3lxw3fb4n2vfzqtyzvxfpb5z/lib/libleveldb.so.1 (0x00002aaaaaaaf000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002aaaaad51000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00002aaaaaf6d000)
	libstdc++.so.6 => /usr/tce/packages/gcc/default/lib64/libstdc++.so.6 (0x00002aaaab270000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00002aaaab57a000)
	libmpi.so.12 => /usr/tce/packages/mvapich2/mvapich2-2.2-intel-18.0.1/lib/libmpi.so.12 (0x00002aaaab782000)
	libpmi2.so.0 => /usr/lib64/libpmi2.so.0 (0x00002aaaabdfa000)
	libgcc_s.so.1 => /usr/tce/packages/gcc/default/lib64/libgcc_s.so.1 (0x00002aaaac015000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00002aaaac22c000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002aaaac5f0000)
	libsnappy.so.1 => /g/g0/sikich1/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/snappy-1.1.7-vg6lrwkynmhutmw7xzywimg4rklyxhun/lib/libsnappy.so.1 (0x00002aaaac7f5000)
	libtcmalloc.so.4 => /usr/lib64/libtcmalloc.so.4 (0x00002aaaac9fd000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
	libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00002aaaacc70000)
	libibverbs.so.1 => /usr/lib64/libibverbs.so.1 (0x00002aaaace7d000)
	libpsm_infinipath.so.1 => /usr/lib64/libpsm_infinipath.so.1 (0x00002aaaad092000)
	libifport.so.5 => /usr/tce/packages/intel/intel-18.0.1/lib/intel64/libifport.so.5 (0x00002aaaad2e8000)
	libifcoremt.so.5 => /usr/tce/packages/intel/intel-18.0.1/lib/intel64/libifcoremt.so.5 (0x00002aaaad518000)
	libimf.so => /usr/tce/packages/intel/intel-18.0.1/lib/intel64/libimf.so (0x00002aaaad8ac000)
	libsvml.so => /usr/tce/packages/intel/intel-18.0.1/lib/intel64/libsvml.so (0x00002aaaade3a000)
	libintlc.so.5 => /usr/tce/packages/intel/intel-18.0.1/lib/intel64/libintlc.so.5 (0x00002aaaaf4ee000)
	libunwind.so.8 => /usr/lib64/libunwind.so.8 (0x00002aaaaf75b000)
	libnl-route-3.so.200 => /usr/lib64/libnl-route-3.so.200 (0x00002aaaaf976000)
	libnl-3.so.200 => /usr/lib64/libnl-3.so.200 (0x00002aaaafbe3000)
	libinfinipath.so.4 => /usr/lib64/libinfinipath.so.4 (0x00002aaaafe04000)
	libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00002aaab0014000)
```

**Comment by MichaelBrim** [comment]
@dsikich libunifycr is also missing from that ldd output. My guess is that the static library is getting added to unifycrd, rather than the dynamic .so. ldd on the client library .so should still show the common library. For the daemon, another way to verify is to use objdump to check that the new common library function symbols are present (e.g., unifycr_error_enum_description)

**Comment by MichaelBrim** [comment]
Never mind on the client library - I haven't added it to the LDFLAGS yet since I didn't integrate with the client side yet. When I do 'objdump -t unifycrd' and grep for 'unifycr_config_' or 'unifycr_error_', I see the symbols from libunifycr_common.

**Comment by dsikich** [comment]
@MichaelBrim I think this is really good.. the only think I would say is that it would be really helpful if you could update the documentation that may apply to this since so much is changing:

http://unifycr.readthedocs.io/en/latest/index.html

You can edit it via the appropriate .rst files in docs/

**Pull request merged**
