### PR TITLE
support cleanup-on-terminate as server CLI option

### PR DESCRIPTION
**Pull request by MichaelBrim**
### Description
Adds `-C,--unifycr-cleanup` as boolean command-line option to server, for use by `unifycr` CLI tool. Updates `unifycr` help to specify `--cleanup` option should be passed in `start` mode.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyCR code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by dsikich** [comment]
@MichaelBrim Can we add a note here in this PR or in the documentation about what this option is expected to clean up? There are spill logs that UnifyCR generates that end up stored on the SSD's, as well as the user data.

**Comment by dsikich** [comment]
@MichaelBrim Looking closer at the PR and thinking about the conversation in the meeting I believe this option isn't functional yet? In that case, I think we should still be explicit that it doesn't do anything until the functionality is added. I think adding a note in say the 'help' menu would be sufficient. It's easy for me to forget which options do/do not work at the rate the interface is changing.

**Comment by MichaelBrim** [comment]
@dsikich  I will update the help/runtime message with a warning that the option is not yet supported. In the follow-on PR when I add the actual cleanup, I can update the documentation/help to be clearer on what is cleaned.

**Comment by dsikich** [comment]
@MichaelBrim Perfect. Thanks.

**Pull request merged**
