### PR TITLE
unifycr_transfer_file, a simple version of data stage operation

### PR DESCRIPTION
**Pull request by sandrain**
- client/src/unifycr.h: added the function prototype
- client/src/unifycr.c: the implementation of the client-side transfer
- client/src/unifycr-sysio.c: change the read(2) to return success on EOF
- examples/src/transfer.c: testing unifycr_transfer_file api

addressing #299 .

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### CODE REVIEW

**Comment by adammoody** [comment]
Thanks @sandrain .  As you discovered, we currently don't handle reporting EOF when reading to the end of a file.  However, I think calling stat should correctly return the file size.  For now, I think you can get something function if you call stat to get the file size, and then manually track reading up to that file size but not beyond.

**Comment by sandrain** [comment]
Hold the merging until I complete the test of creating a file with multiple clients (N-1).

**Comment by sandrain** [comment]
I've tested with four nodes, and test test was successful. I've used the following script:


```
#!/bin/bash

mpirun="mpirun -f nodelist.txt -np 4"

rm -f /tmp/tt*

# stage out
for i in `seq 1 4`; do
    $mpirun `pwd`/prefix/libexec/sysio-write-static -n8 -f testfile$i;
    $mpirun `pwd`/prefix/libexec/sysio-read-static -n8 -f testfile$i;
    $mpirun `pwd`/prefix/libexec/transfer-static /unifycr/testfile$i /tmp/tt$i;
done

# stage in
for i in `seq 1 4`; do
    $mpirun `pwd`/prefix/libexec/transfer-static /tmp/tt$i /unifycr/tt$i;
    $mpirun `pwd`/prefix/libexec/sysio-read-static -n8 -f tt$i
done

```

For stage in, because we only use a single process for transferring, the file data is all written in a single shmem space of the process.

**Comment by adammoody** [comment]
Thanks @sandrain !  This PR is good, although we'll likely need to come back and update the error handling in unifycr_fd_logreadlist().

Your work here led me to uncover some inconsistencies in how we're reading data that I need to look into.  Running this under totalview, I can see the server returns data for a regional of the file that is just before the requested region which is for a block of data beyond the end of the file.  The implementation of unifycr_fd_logreadlist() then detects the mismatch and returns an error, which is what it should do.  I need to debug things further.

**Pull request merged**
