### PR TITLE
Fix testutil create file bug

### PR DESCRIPTION
**Pull request by CamStan**
### Description

When running examples with more than one process and either without UnifyCR or when using file-per-process, this makes sure each process creates the file so that it can be found when opening.

### Motivation and Context

When running the `writeread` example with more than one process and doing file-per-process, only process 0 creates the file and the other processes then cannot find the file when going to open it:
```
jsrun -n2 -a1 -c18 -r1 /prefix/UnifyCR/install/libexec/writeread-static -p nn -n2 -c 4096 -b 16384 -v -f testfile
```
results in:
```
DEBUG: generating write requests
DEBUG: creating target file /unifycr/testfile-0
DEBUG: starting write requests
../../../client/src/unifycr.c:1354 in unifycr_fid_open: /unifycr/-1 does not exist (O_CREAT not given)
```
Not using UnifyCR:

**Update:** this one is fine. See comment [below](https://github.com/LLNL/UnifyCR/pull/336#issuecomment-506843838).
```
jsrun -n2 -a1 -c18 -r1 /prefix/UnifyCR/install/libexec/writeread-posix -p n1 -n2 -c 4096 -b 16384 -v -U -m /dev/shm -f testfile2
```
results in:
```
DEBUG: creating target file /dev/shm/testfile2
DEBUG: generating write requests
DEBUG: starting write requests
[1] ERROR: open(/dev/shm/testfile2) failed (errno=2, No such file or directory)
```
and not using UnifyCR while using file-per-process:
```
jsrun -n2 -a1 -c18 -r1 /prefix/UnifyCR/install/libexec/writeread-posix -p nn -n2 -c 4096 -b 16384 -v -U -m /dev/shm -f testfile3
```
results in:
```
DEBUG: creating target file /dev/shm/testfile3-0
DEBUG: generating write requests
DEBUG: starting write requests
[1] ERROR: open(/dev/shm/testfile3-1) failed (errno=2, No such file or directory)
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### CODE REVIEW

**Comment by CamStan** [comment]
@MichaelBrim, ended up duplicating some code for this since using `-p n1` while using UnifyCR still requires the `test_barrier(cfg)` call. Possibly a better way to fix this.

**Comment by MichaelBrim** [comment]
@CamStan For writeread-posix in single-shared file (-p n1) mode, the mountpoint directory *must* be on a shared file system (/dev/shm is node-local). It should work that way with no changes.

**Comment by CamStan** [comment]
@MichaelBrim, nice catch, thank you. Adjusted this so it only creates for all ranks if file-per-process and the barrier only used if single-shared file.

**Comment by adammoody** [comment]
Thanks @CamStan and @MichaelBrim

**Pull request merged**
